// <auto-generated />
namespace BCModel.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class addEmailToBidPackageInvitation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addEmailToBidPackageInvitation));
        
        string IMigrationMetadata.Id
        {
            get { return "201309230347328_addEmailToBidPackageInvitation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
