// <auto-generated />
namespace BCModel.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class makeBidDateNotNUllable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(makeBidDateNotNUllable));
        
        string IMigrationMetadata.Id
        {
            get { return "201310142115380_makeBidDateNotNUllable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
