// <auto-generated />
namespace BCModel.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class addStateAndCountyToUser : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addStateAndCountyToUser));
        
        string IMigrationMetadata.Id
        {
            get { return "201308212144493_addStateAndCountyToUser"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
