// <auto-generated />
namespace BCModel.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class renameSocialNetwork : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(renameSocialNetwork));
        
        string IMigrationMetadata.Id
        {
            get { return "201401202049011_renameSocialNetwork"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
