// <auto-generated />
namespace BCModel.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class addDateToBlackList : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addDateToBlackList));
        
        string IMigrationMetadata.Id
        {
            get { return "201401251946316_addDateToBlackList"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
