// <auto-generated />
namespace BCWeb.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class _3_20_2013_10_57_am : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_3_20_2013_10_57_am));
        
        string IMigrationMetadata.Id
        {
            get { return "201303301758146_3_20_2013_10_57_am"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
